### ISSUE TITLE
Recent Changes Bug

### ISSUE THREAD

**Issue by opn** [fedwiki/wiki-client#111] opened 2015-04-10 04:55 UTC
Here is a screen cast showing a bug in Recent Changes where Recent Changes is not updated until you reload a page:
- https://www.youtube.com/watch?v=mdC_SKkIRhU

**Comment by paul90** [comment] 2015-04-10 07:36
This will have been caused by the client not updating the local copy of the sitemap as you are creating new pages and editing them.

I would suspect that this was a new, empty, site when you started session you were recording - so the sitemap the client loaded, for fedwiki.org, would have been empty. Recent Changes would just display the data it had, the sitemap for sites.fed.wiki.org plus an empty sitemap for your own site.

This is not a bug in Recent Changes, but a deficiency in the client. Sitemaps are currently not updated once they have been loaded. 

The simple solution is to reload the page, to force the site to be loaded. However, it would be good if somebody could look at keeping the client's copy of the sitemap in step as pages are added and edited.

**Comment by paul90** [comment] 2016-07-11 16:14
Closing as this issue was addressed by #158

**Closed by paul90** 2016-07-11 16:14 UTC
