### ISSUE TITLE
Wiki is hijacking parent iframe's link targets.

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-client#106] opened 2015-03-22 15:08 UTC
Forged from #93 

---

Pasting a monologue of me from `#fedwiki`.

---

Good day everyone.
I'm trying to fix a minor issue with integrating fedwiki in a [hackfoldr](https://github.com/allmende/hackfoldr-2.0/) mashup.

The issue:

1. When opening http://hack.transforlab.net and clicking on any despite the "TransforLab" link (depending on your resolution, you have to unfold the folder list) opens everything in the desired iframe.
2. After opening the Federated Wiki, all links, also from the `hackfoldr` navigation, get routed to new tabs/a new tab.

The questions:
1. How can wiki escape the iframe and alter the original application's behaviour?
2. How do I stop it from doing so?

Any help appreciated.

The issue seems to reside around https://github.com/fedwiki/wiki-client/pull/93/files and https://github.com/fedwiki/wiki-client/blob/d4bd7e8adb16c664187760308b0b3825070b6554/lib/refresh.coffee , if I'm not mistaken.

Somehow https://github.com/fedwiki/wiki-client/blob/d4bd7e8adb16c664187760308b0b3825070b6554/lib/refresh.coffee#L154 is it. Don't know how to circumvent it altering the parent frame context, too.

Only blocking scripts via a sandboxed iframe helps here, but then I also lose the dynamic lineup. http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/

---

I am helping myself now by opening wiki links in a new tab themselves only, so they don't override the `hackfoldr` link behaviour. But it would be nice to be able to integrate it in such a meta navigation as hackfoldr offers.

---

And answering to @paul90 in https://github.com/fedwiki/wiki-client/pull/93#issuecomment-84625436

I have not changed any line of code in wiki. From my perspective the questions above remain. I have removed the `_blank` target from one of the Federated Wiki links, so you should be able to experience the issue when opening the respective one.

**Comment by paul90** [comment] 2015-03-22 16:13
The feature added in #93, which is all about resolving a major problem caused by a change of origin in the current tab - which requires that the tabs used by the wiki are programmatically named is unlikely to behave well in the context of an iframe.

> After opening the Federated Wiki, all links, also from the hackfoldr navigation, get routed to new tabs/a new tab.

This in all probability be being causes by `window.name` being set by the client, and it not being what your wrapper is expecting - so it is opening a new tab as the iframe is no longer named what you are expecting.

It is highly likely this is what is causing your problems with trying to use the wiki client inside an iframe.

A simple change would be for the client to detect if it is being loaded in an iframe, and not to get the `window.name` if it is. *Though note, any wiki links that would change the page's origin will still open in a new tab.*

An alternative solution might be, in hackfoldr, to doubly wrap the with iframes.

**Comment by almereyda** [comment] 2015-03-22 17:37
Thanks for this precise answer. I will try to further investigate the issue.

**Comment by paul90** [comment] 2016-07-19 13:38
closing as over a year since last updated

**Closed by paul90** 2016-07-19 13:38 UTC
