### ISSUE TITLE
Remote wiki pages in the lineup don't get loaded

### ISSUE THREAD

**Issue by almereyda** [fedwiki/wiki-client#150] opened 2016-02-21 16:20 UTC
I have been stumbleing in a wiki conversation and found I couldn't link to a specific lineup including remote pages anymore.

As seen on http://jon.mitte.tries.fed.wiki/view/welcome-visitors/jon.wiki.allmende.io/jon-richter

**Comment by WardCunningham** [comment] 2016-02-21 19:16
Jon -- I clicked the "older" twin and found it opened a remote page. I was browsing with chrome. If this was failing for you, or failing with a different browser, please let me know details. Also, thanks for returning to "mitte" conversation. I'll write something there today. Best regards -- Ward

**Comment by paul90** [comment] 2016-02-22 10:08
This problem was caused by a change in an underlying library resulting in the `.`s in the url getting escaped.

This problem is resolved in **wiki-client@0.7.3**, which has just been published.

**Comment by WardCunningham** [comment] 2016-02-22 14:31
I'm sorry. I didn't understand the issue. I do now.
This is the commit that fixed the problem: https://github.com/fedwiki/wiki-client/commit/c613c8f3ffe64ec5881b8cdaa5e620a96de6883a

I've installed the new version for all tries.fed.wiki sites.

**Comment by paul90** [comment] 2016-07-11 16:11
Closing as issue resolved.

**Closed by paul90** 2016-07-11 16:11 UTC
